#Trabajo Práctico Redes Neuronales
####Agustina Schajris Garati 4to C

Mi dataset consiste en varios casos de personas con COVID 19 y la gravedad de su condición. Mi tarea es predecir, dependiendo de los síntomas que tenga una persona, si la gravedad de su envermedad es leve, moderada, severa o nula. Es un problema de clasificación multiclase.

Mi dataset: [COVID-19 Symptoms Checker](https://www.kaggle.com/datasets/iamhungundji/covid19-symptoms-checker)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import HTML, display
import tabulate
import networkx as nx
from random import random as rand
import itertools
import tensorflow as tf
import math

In [2]:
np.random.seed(1)

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
data = pd.read_csv('/content/drive/MyDrive/Cleaned-Data.csv')
data

Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0           1          1          1                        1            1   
1           1          1          1                        1            1   
2           1          1          1                        1            1   
3           1          1          1                        1            1   
4           1          1          1                        1            1   
...       ...        ...        ...                      ...          ...   
316795      0          0          0                        0            0   
316796      0          0          0                        0            0   
316797      0          0          0                        0            0   
316798      0          0          0                        0            0   
316799      0          0          0                        0            0   

        None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \
0                  0      1                 1           1         1  ...   
1                  0      1                 1           1         1  ...   
2                  0      1                 1           1         1  ...   
3                  0      1                 1           1         1  ...   
4                  0      1                 1           1         1  ...   
...              ...    ...               ...         ...       ...  ...   
316795             1      0                 0           0         0  ...   
316796             1      0                 0           0         0  ...   
316797             1      0                 0           0         0  ...   
316798             1      0                 0           0         0  ...   
316799             1      0                 0           0         0  ...   

        Gender_Male  Gender_Transgender  Severity_Mild  Severity_Moderate  \
0                 1                   0              1                  0   
1                 1                   0              1                  0   
2                 1                   0              1                  0   
3                 1                   0              0                  1   
4                 1                   0              0                  1   
...             ...                 ...            ...                ...   
316795            0                   1              0                  0   
316796            0                   1              0                  0   
316797            0                   1              0                  0   
316798            0                   1              0                  0   
316799            0                   1              0                  0   

        Severity_None  Severity_Severe  Contact_Dont-Know  Contact_No  \
0                   0                0                  0           0   
1                   0                0                  0           1   
2                   0                0                  1           0   
3                   0                0                  0           0   
4                   0                0                  0           1   
...               ...              ...                ...         ...   
316795              0                1                  0           1   
316796              0                1                  1           0   
316797              1                0                  0           0   
316798              1                0                  0           1   
316799              1                0                  1           0   

        Contact_Yes  Country  
0                 1    China  
1                 0    China  
2                 0    China  
3                 1    China  
4                 0    China  
...             ...      ...  
316795            0    Other  
316796            0    Other  
316797            1    Other  
316798            0    Other  
316799            0    Othe

In [5]:
#Función sigmoide, una de muchas funciones de activación. Lo que hace es, agarrando cualquier número real, devolver un valor cercano a 0 si la entrada es muy negativa, un valor cercano a 1 si la entrada es muy positiva y alrededor de 0.5 si la entrada es cercana a 0.; es una aproximación. Se utiliza para introducir no linealidad en la red.
def sigmoid(x):
    return 1 / ( 1 + np.exp(-x) )

#Función derivada de la sigmoide que se usa en el proceso de backpropagation para calcular los ajustes de los pesos.
def sigmoid_derivative(x):
    return x * (1 - x)

#Función de activación softmax para clasificación multiclase. Lo que hace es convertir un vector de valores de entrada en un vector de probabilidades(cada elemento del vector de salida representa la probabilidad de pertenencia a una clase específica).
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

In [6]:
columnas_input = list(range(0, 19)) + list(range(23, 26))
columnas_output = list(range(19, 23)) #multiclase

training_inputs = data.iloc[:, columnas_input]
training_outputs = data.iloc[:, columnas_output]

In [7]:
columnas_input

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23, 24, 25]

In [8]:
columnas_output

[19, 20, 21, 22]

In [9]:
#Weights
n = training_inputs.shape[1] #número de entradas
m = training_outputs.shape[1] #número de salidas

#Fijo los weights de manera aleatoria cerca de cero. Después, esos números se van a ir ajustando en el entrenamiento.
synaptic_weights = 2 + np.random.random((n, m)) - 1

##Training

In [10]:
eval_NN = lambda x, w: sigmoid(np.dot(x, w))

In [11]:
#500 epochs
for iteration in range(500):

    input_layer = training_inputs

    #FORWARD PROPAGATION
    #Multiplico los inputs por los weights y los paso por la función de activación softmax para obtener las salidas de la red.
    #Uso la función softmax ya que me permite convertir m salida en la probabilidad de pertenencia a cada clase. Es útil para tareas de clasfificación.
    outputs = eval_NN(input_layer, synaptic_weights)
    softmax_outputs = softmax(outputs)

    #Calculo el error comparando las salidas reales y las salidas predichas para usarlo en backpropagation.
    error = training_outputs - softmax_outputs

    #BACKPROPAGATION
    #Uso el error para ajustar los weights usando la derivada de la función sigmoide. Uso la gradiente descendente para acercarme al punto con menor error más cercano, y así, ir ajustando los weights para hacer mejores predicciones.
    adjustments = error * sigmoid_derivative(softmax_outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)

In [12]:
print('Synaptic weights after training')
print(synaptic_weights)

print('Outputs after training: ')
print(outputs)

Synaptic weights after training
[[40.47892061 40.78221654 40.06201088 40.36422794]
 [63.64579825 63.59136376 63.68531438 63.84460921]
 [71.70819833 71.85022861 71.73063898 71.9966606 ]
 [63.70349622 64.3771527  63.52643787 64.1695233 ]
 [40.4792037  40.62058164 40.20228651 40.25999548]
 [ 9.61311576  9.7806348   9.12578954  9.50468991]
 [47.33023731 47.34844574 46.53888714 46.49288826]
 [69.35059413 70.05890561 69.27912723 69.60188525]
 [70.13867338 69.71392392 69.87267198 69.49629384]
 [47.14034725 47.2884635  46.47213226 47.2039981 ]
 [13.35231042 13.11161485 12.64388722 13.15272984]
 [26.10282793 26.44750095 26.90821062 26.29321678]
 [26.28738184 26.12963211 26.01895502 26.67844719]
 [26.21123283 26.26515201 26.49117851 26.05295751]
 [26.57372972 26.14633235 26.58891355 26.69937041]
 [26.10193633 26.41366306 26.69401077 26.41378511]
 [42.71595103 43.20190327 43.32980511 43.18090775]
 [43.61062241 43.25256303 43.56942223 42.8034783 ]
 [42.80527827 43.47340358 43.06367321 42.83135911]

In [13]:
Fever = 1 #@param {type:"integer"}
Tiredness = 1 #@param {type:"integer"}
Dry_Cough = 0 #@param {type:"integer"}
Difficulty_in_Breathing = 1 #@param {type:"integer"}
Sore_Throat = 1 #@param {type:"integer"}
None_Sympton = 0 #@param {type:"integer"}
Pains = 1 #@param {type:"integer"}
Nasal_Congestion = 1 #@param {type:"integer"}
Runny_Nose = 0 #@param {type:"integer"}
Diarrhea = 0 #@param {type:"integer"}
None_Experiencing = 0 #@param {type:"integer"}
Age_0_9 = 1 #@param {type:"integer"}
Age_10_19 = 0 #@param {type:"integer"}
Age_20_24 = 0 #@param {type:"integer"}
Age_25_59 = 0 #@param {type:"integer"}
Age_60up = 1 #@param {type:"integer"}
Gender_Female = 0 #@param {type:"integer"}
Gender_Male = 1 #@param {type:"integer"}
Gender_Transgender = 0 #@param {type:"integer"}
Contact_Dont_Know = 0 #@param {type:"integer"}
Contact_No = 0 #@param {type:"integer"}
Contact_Yes = 1 #@param {type:"integer"}


input_layer = np.array([Fever, Tiredness, Dry_Cough, Difficulty_in_Breathing,
       Sore_Throat, None_Sympton, Pains, Nasal_Congestion,
       Runny_Nose, Diarrhea, None_Experiencing, Age_0_9, Age_10_19,
       Age_20_24, Age_25_59, Age_60up, Gender_Female, Gender_Male,
       Gender_Transgender, Contact_Dont_Know, Contact_No, Contact_Yes])

outputs = np.dot(input_layer, synaptic_weights)
softmax_outputs = softmax(outputs) #uso la función softmax para porder sacar las probabilidades

probability_mild = math.trunc(softmax_outputs[0] * 100) / 100
probability_moderate = math.trunc(softmax_outputs[1] * 100) / 100
probability_none = math.trunc(softmax_outputs[2] * 100) / 100
probability_severe = math.trunc(softmax_outputs[3] * 100) / 100

print("Probability mild: " + str(probability_mild))
print("Probability moderate: " + str(probability_moderate))
print("Probability severe: " + str(probability_severe))
print("Probability none: " + str(probability_none))

Probability mild: 0.05
Probability moderate: 0.83
Probability severe: 0.06
Probability none: 0.04
